### ISSUE TITLE
Question on second script

### ISSUE THREAD

**Issue by fibke** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#1]
The folds.RDS file seems to be unavailable. When running, this is the error one gets:

> folds <- readRDS("output-data/folds.RDS")
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'output-data/folds.RDS', probable reason 'No such file or directory'

**Comment by sondreus** [comment]
Now added - thanks for flagging. The pre-generated folds are useful for the calibration plot (and using the same folds is also useful to compare this model to other approaches).
