### ISSUE TITLE
GDP data

### ISSUE THREAD

**Issue by akarlinsky** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#13]
Seems to be missing for Taiwan (https://github.com/TheEconomist/covid-19-the-economist-global-excess-deaths-model/blob/main/source-data/world_bank_nominal_gdp.csv), perhaps other countries as well. 
How does the model treat it?

**Comment by sondreus** [comment]
Yes: https://data.worldbank.org/indicator/NY.GDP.MKTP.PP.KD?locations=TW

Treated like any other missing data. I can check which other countries it is missing for.

**Comment by sondreus** [comment]
Missing for these countries: 
```
Anguilla	AIA	NA
3893	Andorra	AND	NA
11435	Caribbean Netherlands (Bonaire, Sint Eustatius and Saba)	BES	NA
28465	Cook Islands	COK	NA
32196	Cuba	CUB	NA
45013	Falkland Islands	FLK	NA
46148	Faroe Islands	FRO	NA
50000	NA	GGY	NA
51340	Gibraltar	GIB	NA
56083	Greenland	GRL	NA
62897	Isle of Man	IMN	NA
72630	NA	JEY	NA
83337	Liechtenstein	LIE	NA
88932	Monaco	MCO	NA
98258	Montserrat	MSR	NA
102193	New Caledonia	NCL	NA
104509	Niue	NIU	NA
110716	Pitcairn	PCN	NA
115302	North Korea	PRK	NA
117540	French Polynesia	PYF	NA
123981	St. Helena Ascension and Tristan da Cunha	SHN	NA
134812	Syria	SYR	NA
139070	Tokelau	TKL	NA
144787	Taiwan	TWN	NA
149658	Vatican	VAT	NA
151806	Virgin Islands (British)	VGB	NA
153311	Wallis and Futuna	WLF	NA
```
All make sense to me to be NA on brief inspection. Is there another source with more complete data perhaps? (For why Taiwan is missing: https://datahelpdesk.worldbank.org/knowledgebase/articles/114933-where-are-your-data-on-taiwan)

**Comment by akarlinsky** [comment]
IMF has data for Taiwan and perhaps others here: https://www.imf.org/en/Publications/WEO/weo-database/2021/April/download-entire-database

For Cuba I used data from CIA world factbook: 
https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita

**Comment by sondreus** [comment]
Now added
