### ISSUE TITLE
Where is the demography-adjusted infection fatality rate?

### ISSUE THREAD

**Issue by stevepowell99** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#16]
(A question rather than an issue)
In https://www.economist.com/graphic-detail/coronavirus-excess-deaths-estimates you report how you used the Demography-adjusted infection fatality rate, but I wasn't able to find this in the source data?

**Comment by sondreus** [comment]
Hi @stevepowell99, happy to help:

You can find the file used by the models in this repo here:
https://github.com/TheEconomist/covid-19-the-economist-global-excess-deaths-model/blob/main/source-data/ifr_cache.RDS

This file is based on the estimates generated here:
https://github.com/TheEconomist/covid-19-age-adjusted-ifr

The latter repo also details my approach, and links to article in which they were first published.
