### ISSUE TITLE
Question: Why Filter out U.S. State of Georgia?

### ISSUE THREAD

**Issue by jschulberg** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#2]
Hi all, great work on the code, model, and visualizations with this! Just curious why you [filter out the U.S. State of Georgia](https://github.com/TheEconomist/covid-19-the-economist-global-excess-deaths-model/blob/main/scripts/1_excess_deaths_global_estimates_script.R#L43) in your first script.
Thanks,
Justin

**Comment by sondreus** [comment]
Hi Justin. Thank you for the kind words. This is just to avoid any potential conflation with the country of Georgia! The iso3c mapping through countrycode builds on area names, hence the possibility for confusion and need to avoid it. Hope this helps.

All the best,
Sondre
