### ISSUE TITLE
Question on baseline of expected deaths

### ISSUE THREAD

**Issue by dFila** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#22]
Hi there,

I was trying to find the baseline of global expected mortality for the entire year (Jan 1 - Dec 31) in 2020 and in 2021. I was able to find the global excess mortality estimates and the expected mortality by country, but I could not find the number of global expected deaths used to calculate the "central excess death estimate" figures published by Our World in Data (16.99M from Jan 1, 2020 to Dec 20, 2021).

https://ourworldindata.org/excess-mortality-covid#estimated-excess-mortality-from-the-economist

Specifically, I am looking for the “central” estimate for the following:
global ACM in 2020 (Jan 1 - Dec 31)
global ACM in 2021 (Jan 1 - Dec 31)
global expected mortality in 2020 (Jan 1 - Dec 31)
global expected mortality in 2021 (Jan 1 - Dec 31)

Also, what is meant by “central” excess death estimate? Is it the median or the mean of the models used?

Thanks

**Comment by dFila** [comment]
It does. Could you please elaborate on how you estimate excess mortality directly without ACM and expected ACM? I thought that was the definition of excess mortality, the difference between the two.

**Comment by sondreus** [comment]
Sure, full details are here: https://www.economist.com/graphic-detail/2021/05/13/how-we-estimated-the-true-death-toll-of-the-pandemic

Essentially, one does not need to know the subcomponent of something to estimate it (much like how one can estimate GDP without breaking it into its constituent parts). We have ACM and expected ACM for some countries, with the details here: https://www.economist.com/graphic-detail/coronavirus-excess-deaths-tracker. We use this to come up with excess deaths figures for the these countries. We then use these excess deaths figures as our training data, and estimate it directly.

Hope this helps!

**Comment by dFila** [comment]
Also, the quotes below led me to believe that The Economist did estimate expected deaths. From the article:

https://www.economist.com/graphic-detail/coronavirus-excess-deaths-tracker

“We have used statistical models to create our baselines, by predicting the number of deaths each region would normally have recorded in 2020 and 2021”

“Update (October 14th 2020): A previous version of this page used a five-year average of deaths in a given region to calculate a baseline for excess deaths. The page now uses a statistical model for each region, which predicts the number of deaths we might normally have expected in 2020”

**Comment by dFila** [comment]
My apologies, I did not see your previous reply.

**Comment by sondreus** [comment]
No problem. Did my reply clarify sufficiently?

**Comment by dFila** [comment]
^ https://www.economist.com/graphic-detail/coronavirus-excess-deaths-tracker

**Comment by sondreus** [comment]
Yes, 2015-2019, with a week, month or quarter fixed effects and a year trend. You can find the details and code here: https://github.com/TheEconomist/covid-19-excess-deaths-tracker

**Comment by dFila** [comment]
Thank you for taking the time to answer my questions.
