### ISSUE TITLE
country_daily_excess_deaths_with_covariates.csv is missing from output

### ISSUE THREAD

**Issue by peterszklenar** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#4]
Is it possible to share the combined csv file to use for model input? Thanks

**Comment by sondreus** [comment]
Hi Peter, unfortunately the file is too large for github as a csv (over 100mb), I'm working on an update which gets around the issue by using RDS files.

**Comment by sondreus** [comment]
Hi - sorry about the delay, just pushed this extra feature just now. You can uncomment the second command of the export script to load an RDS file I just added, if you do not want to create the csv file yourself.

**Comment by peterszklenar** [comment]
Hi, Thanks so much!!
