### ISSUE TITLE
Argentina's estimate

### ISSUE THREAD

**Issue by JoseMenendezASU** [TheEconomist/covid-19-the-economist-global-excess-deaths-model#6]
Folks: if I am reading your data correctly, for calendar year 2020 your model indicates about 72K excess deaths for Argentina. However, the Health Ministry (https://www.argentina.gob.ar/noticias/el-ministerio-de-salud-presento-estudio-sobre-exceso-de-mortalidad-en-2020-por-covid-19) did a study which I guess is more based on actual data, and they find 36K excess deaths. This is not too far from OurWorldinData's estimate of 41 K. Official COVID deaths in Argentina for 2020 are 46 K (covidstats.com.ar) or 43 K (OurWorldinData). It appears that previous excess death estimates nicely agree with official COVID numbers. Your estimate, on the other hand, is 60% higher. It smells like an outlier...

**Comment by romunov** [comment]
Excessive excessive deaths? :)

**Comment by sondreus** [comment]
Hi @JoseMenendezASU

Thanks for pointing this out! I did not know of this Argentina data (Ariel Karlinsky also pointed this out to me yesterday). This model pulls excess deaths data dynamically from our tracker, I've opened an issue there to get it checked and included (I've also pinged the person who maintains that repo through internal channels). The Argentina's study count for 2020 is indeed lower than our estimate, which is good news in the sense that there are about 30 thousand fewer excess deaths than we project for 2020. 

https://github.com/TheEconomist/covid-19-excess-deaths-tracker/issues/18

Once it enters the tracker, it will enter this model too and give us better estimates for Argentina, which is great. As we continue to update the model, it will also inform predictions elsewhere. If you find any other sources of data we have missed, do not hesitate to point them out so we can improve this model as much as possible.

**Comment by sondreus** [comment]
@JoseMenendezASU @romunov 

Hi both - this is now in, along with Guatemala, Hong Kong, and several small countries/territories, as well as a transition of Iran data from quarterly to weekly. The excess deaths tracker repo has also been rewritten to facilitate more rapid inclusion of new countries as they get added to the data sources elsewhere. 

Our confidence intervals have narrowed as a result of the new data, though for the world total numbers our central estimate is near-identical (in Argentina excess was lower than central estimate, in Hong Kong higher, iirc). For Argentina in particular, it is worth noting that the reported total mortality data ends in 2020, meaning our total estimate is and should be higher than that reported in those (as it goes all the way to the present). 

These data will also go into the next round of model training, improving the model further as the pandemic progresses and we get more training data. Thanks again for pointing out that this data was available.
